### ISSUE TITLE
PF_riverBasinDistrict_The attribute is wrong encoded

### ISSUE THREAD

**Issue by fabiovin** [INSPIRE-MIF/application-schemas#1]
# Change proposal description
The attribute riverBasinDistrict should be encoded in the right way.

## Issue faced
The attribute riverBasinDistrict is not encoded correctly because its multiplicity is 0..1 and the dataType is a codelist.

## Proposed solution
It should be encoded in this way:

![image](https://user-images.githubusercontent.com/46569952/117418885-39499200-af1c-11eb-8bea-dd96c0a72c10.png)

 
### Technical details
Related pull request: https://github.com/INSPIRE-MIF/application-schemas/pull/2

# Additional information

## Proposal reason
Bugfix

## Addressed schema
https://inspire.ec.europa.eu/schemas/pf/4.0/ProductionAndIndustrialFacilities.xsd 

## Impact on INSPIRE TG / IR
No impact on TG/IR.

**Comment by sMorrone** [comment]
Subgroup meeting 01-07-2021: the sub-group approves the change proposal and invites the INSPIRE Coordination Team (CT) to endorse it.

**Comment by MarcoMinghini** [comment]
The INSPIRE CT approved the change proposal during today's meeting. In the next step, the proposal will be moved to the MIG for the final endorsement.

**Comment by MarcoMinghini** [comment]
The INSPIRE MIG approved the change proposal, since no objections were raised during the two week scrutiny period from July 12 to July 26, 2021. The change can be now implemented.

**Comment by Dnoack49** [comment]
PF_type_missing xlink structure for codelist attribute #64
