### ISSUE TITLE
OM__TimeLocationValueTriple_provision of the value not allowed 

### ISSUE THREAD

**Issue by sMorrone** [INSPIRE-MIF/application-schemas#10]
# Change proposal description
Proposal is modify the TimeLocationValueTriple in the https://inspire.ec.europa.eu/schemas/omso/3.0/SpecialisedObservations.xsd. It is currently derived from _wml2:TimeValuePair_ , proposal is to derive it from _**wml2:MeasurementTVP**_ .

## Issue faced
The datatype TimeLocationValueTriple provided in the current SpecialisedObservations schema only covers the spatiotemporal aspects, thus not allowing for the provision of a value.

### Expected behaviour
The TimeLocationValueTriple allows for provision of time + value + location of a measurement

### Current behaviour
 in the SpecialisedObservations schema, the  TimeLocationValueTriple data type only provides time + location

## Proposed solution
Underlying issue had to do with errors in WaterML 2.0 with TimeValuePairType with only time. Proposal is to use same fix already used for WaterML 2.0 i.e. the introduction of the the MeasureTVPType (with both time and value). Deriving the TimeLocationValueTriple from MeasureTVPType will solve current issue.

### Technical details
![image](https://user-images.githubusercontent.com/13329248/122088945-8fa4cd00-ce06-11eb-936b-c8d532357228.png)

# Additional information

## Proposal reason
proposal is needed because of a bug 

## Addressed schema
https://inspire.ec.europa.eu/schemas/omso/3.0/SpecialisedObservations.xsd

## Impact on INSPIRE TG / IR
no impact

### More detailed documentation
Proposed modifications to the TimeLocationValueTriple are highlighted in the below screenshot (on the left the current data type, on the right the modified one)

![triple](https://user-images.githubusercontent.com/13329248/124389982-e60c7980-dce9-11eb-917a-a1036e77030c.png)

and provided here: 
http://datacove.eu/data/documents/TimeLocationValueTriple.xsd

**Comment by sMorrone** [comment]
Subgroup meeting 01-07-2021: the sub-group approves the change proposal and invites the INSPIRE Coordination Team (CT) to endorse it. I volunteered to add a relevant pull request.

**Comment by sMorrone** [comment]
Related pull request: https://github.com/INSPIRE-MIF/application-schemas/pull/16

**Comment by MarcoMinghini** [comment]
The INSPIRE CT approved the change proposal during today's meeting. In the next step, the proposal will be moved to the MIG for the final endorsement.
