### ISSUE TITLE
Typo in theme in enum XSD

### ISSUE THREAD

**Issue by arbakker** [INSPIRE-MIF/application-schemas#11]
There is a typo in the Dutch INSPIRE theme [enumerations XSD (line 22)](https://inspire.ec.europa.eu/schemas/common/1.0/enums/enum_dut.xsd), for theme _Natural risk zones_ :

```
<xs:enumeration value="Gebieden met natuurrisico'es"/>
```

Should be:

```
<xs:enumeration value="Gebieden met natuurrisico's"/>
```

This is a problem, since GeoNetwork uses the correctly spelled version, which results in invalid metadata (ISO metadata and capabilities docs). At least this is the case for the GN version running at the Dutch national geoportal at https://nationaalgeoregister.nl/geonetwork.

**Comment by heidivanparys** [comment]
There is indeed a typo:

https://github.com/INSPIRE-MIF/application-schemas/blob/7e5c57bc7913360fa36da164737f89d11f7d4871/schemas/common/1.0/enums/enum_dut.xsd#L22

The text should match the text in the [INSPIRE registry](https://inspire.ec.europa.eu/theme), where the typo is not present.

@arbakker 
I moved this issue to the repository dedicated to managing changes to the INSPIRE XML schemas.

In order to help the governance and release process move forward, please copy, paste and fill out the [change proposal template](https://raw.githubusercontent.com/INSPIRE-MIF/application-schemas/main/.github/ISSUE_TEMPLATE/change-proposal.md) to the best of your knowledge.

**Comment by arbakker** [comment]
# Change proposal description

Fix typo in the Dutch INSPIRE theme [enumerations XSD](https://inspire.ec.europa.eu/schemas/common/1.0/enums/enum_dut.xsd) (line 22), for theme _Natural risk zones_.

## Issue faced

N/A

### Expected behaviour

N/A

### Current behaviour

N/A

### Steps to reproduce

N/A

## Proposed solution

Fix typo in the Dutch INSPIRE theme [enumerations XSD](https://inspire.ec.europa.eu/schemas/common/1.0/enums/enum_dut.xsd) (line 22), for theme Natural risk zones :

```
<xs:enumeration value="Gebieden met natuurrisico'es"/>
```

Should be:

```
<xs:enumeration value="Gebieden met natuurrisico's"/>
```

So value in the schema matches the text in the [INSPIRE registry](https://inspire.ec.europa.eu/theme).


### Technical details

See https://github.com/INSPIRE-MIF/application-schemas/pull/12

# Additional information

## Proposal reason

Stumbled on metadata record that would not validate against ETF validator, where the value without  typo was used. Since the official schema contains the typo. 

## Addressed schema

- [enum_dut.xsd](https://inspire.ec.europa.eu/schemas/common/1.0/enums/enum_dut.xsd)

## Impact on INSPIRE TG / IR

No impact, as far as I can tell. 

## Change proposer

- anton.bakker at kadaster.nl

## References
### Available implementation

N/A

### More detailed documentation

N/A

**Comment by heidivanparys** [comment]
Subgroup meeting 01-07-2021: Newer and unofficial versions of the "common" schemas are present at https://inspire-geoportal.ec.europa.eu/schemas/ (including https://inspire-geoportal.ec.europa.eu/schemas/inspire/common/1.0/enums/enum_dut.xsd). Those newer versions should be submitted in this repository, going through the governance process. When those changes are approved, this typo issue will also be solved, as the typo already was corrected there.

**Comment by sMorrone** [comment]
During the meeting, it was highlighted that a schema versioning is needed, otherwise already published documents with incorrect spelling (valid according to current schema) would not validate against the corrected schema.

**Comment by MarcoMinghini** [comment]
The INSPIRE CT approved the change proposal during today's meeting. In the next step, the proposal will be moved to the MIG for the final endorsement.

**Comment by MarcoMinghini** [comment]
The INSPIRE MIG approved the change proposal, since no objections were raised during the two week scrutiny period from July 12 to July 26, 2021. The change can be now implemented.
