### ISSUE TITLE
PF_ProductionFacility_groupingFacility association missing

### ISSUE THREAD

**Issue by JohannaOtt** [INSPIRE-MIF/application-schemas#126]
# Change proposal description

## Issue faced
According to the [UML diagram](https://inspire-mif.github.io/uml-models/approved/html/EARoot/EA2/EA3/EA15/EA1/EA8998.htm), `ProductionInstallation` should have an association called `groupingFacility` linking to the respective `ProductionFacility` object. But in the related [xsd](https://inspire.ec.europa.eu/schemas/pf/4.0/ProductionAndIndustrialFacilities.xsd), no such association is defined.

### Expected behaviour
I would expect `ProductionFacility.groupingFacility` to be contained in the xsd file

### Current behaviour
`ProductionFacility.groupingFacilit`y is missing in the xsd file

## Proposed solution
Add `groupingFacility` to the xsd file

# Additional information

## Proposal reason
I think it is a bug that the xsd file does not reflect what is defined in the respective UML model. It would be really useful for data users IMO to have a link to the `ProductionFacility` a `ProductionInstallation` belongs to.

## Addressed schema
[ProductionAndIndustrialFacilities.xsd](https://inspire.ec.europa.eu/schemas/pf/4.0/ProductionAndIndustrialFacilities.xsd)

## Change proposer
The `groupingFacility `association would also need to be added to the [Implementing rules](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32010R1089&qid=1721741594119) as well as the [Data specification](https://github.com/INSPIRE-MIF/technical-guidelines/blob/main/data/pf/dataspecification_pf.pdf)

**Comment by fabiovinci** [comment]
Dear @JohannaOtt,

thank you for your proposal.
It is similar to issue #123 already discussed and rejected by the Sub-group.

It seems that all the associations in the PF data model were modelled as "navigable only in one direction", as recommended in the Generic Conceptual Model document.

In any case, the proposal will be discussed in the next Sub-group meeting.

**Comment by JohannaOtt** [comment]
@fabiovinci Thanks a lot for the quick response and the link to the other issue. I seemed to remember that something similar had been discussed but did not find it with my keywords ;)
If it is decided to go with associations in one direction, I would change this CR to remove the additional associations from the UML model. This way implementers will not be confused any longer.

**Comment by fabiovinci** [comment]
Sub-group meeting on 11.11.2024:
The sub-group reviewed the suggestion to remove the association roles from the UML and decided to retain the roles in the association properties while hiding them in the diagram.

This solution will maintain clear documentation of roles associated with different feature types, helping to avoid confusion caused by their visibility in the UML diagram.

These updates will be implemented in the upcoming release scheduled for the end of January 2025.


![image](https://github.com/user-attachments/assets/559a6809-fac5-4fb5-af69-9e45bec222b7)
