### ISSUE TITLE
https://inspire.ec.europa.eu/schemas/af/4.0/AgriculturalAndAquacultureFacilities.xsd not available

### ISSUE THREAD

**Issue by KnorrAn** [INSPIRE-MIF/application-schemas#129]
Hello everyone,

The XSD schema for AgriculturalAndAquacultureFacilities https://inspire.ec.europa.eu/schemas/af/4.0/AgriculturalAndAquacultureFacilities.xsd is currently not available. The following error is displayed (in German): 

![grafik](https://github.com/user-attachments/assets/f2b23029-7941-421c-bf04-2389838144e9)

Can anybody help?

Regards and thanks
Antje

**Comment by fabiovinci** [comment]
Dear @KnorrAn,

thank you for the notification, we will have a look as soon as possible.

In the meantime, I tried to open the schema with transformation software (i.e. hale studio) and it works.

You can also temporarily use the previous version: "https://inspire.ec.europa.eu/schemas/2024.1/af/4.0/AgriculturalAndAquacultureFacilities.xsd

**Comment by fabiovinci** [comment]
Dear @KnorrAn,

the schema works now.
Please inform us if the error continues to occur.

**Comment by KnorrAn** [comment]
Thanks a lot @fabiovinci!
