### ISSUE TITLE
PS_ProtectedSite_rename inspireID to inspireId

### ISSUE THREAD

**Issue by sMorrone** [INSPIRE-MIF/application-schemas#13]
# Change proposal description
Within the theme of Protected Sites the INSPIRE identifier is spelled as “inspireID” and not as “inspireId”. It is proposed to harmonise the name of the inspire identifier attribute and to use inspireId in the INSPIRE Protected sites theme.

This proposal has already been approved and is contained in the [corrigendum on protected sites](https://inspire.ec.europa.eu/file/1624/download?token=PzarY4jx)

## Proposal reason
Harmonisation of the spelling of the inspireId attribute throughout the INSPIRE data themes.

## Addressed schema
https://inspire.ec.europa.eu/schemas/ps/4.0/ProtectedSites.xsd

## Impact on INSPIRE TG / IR
impacts the Technical Guidance documents (TG) and the Implementing Rules (IR)

**Comment by doemming** [comment]
will this change also update the version (namespace) of the PS schema?

**Comment by sMorrone** [comment]
Subgroup meeting 01-07-2021: additional modifications proposed by the EEA related to the PS schema were already submitted for update of the IR (and included in a draft version document) and are described in issue https://github.com/INSPIRE-MIF/application-schemas/issues/14 . These do not need to undergo the overall governance process and are going directly through the Comitology procedure. To avoid releasing two different schema versions in a short time, the modification related to the InspireId will be implemented together with those in https://github.com/INSPIRE-MIF/application-schemas/issues/14
