### ISSUE TITLE
US_EnvironmentalManagementFacility_missing 'EnvironmentalManagementFacility' type + incomplete 'parentFacility' 

### ISSUE THREAD

**Issue by sMorrone** [INSPIRE-MIF/application-schemas#4]
# Change proposal description
Proposal is to add missing _type_ to the 'EnvironmentalManagementFacility' element definition + add missing parts in the definition of 'parentFacility' element

## Issue faced
EnvironmentalManagementFacility element is missing own type definition + parentFacility association has incomplete definition

### Expected behaviour
it is possible to create environmental management facility objects and related parent facility objects.

### Current behaviour
it is not possible to create environmental management facility spatial objects  + it is not possible to specify parent facilities

## Proposed solution

- add the type to the EnvironmentalManagementFacility  element as follows:

![image](https://user-images.githubusercontent.com/13329248/121516180-398eee80-c9ee-11eb-8f31-db5957a1b82c.png)

- specify content of the parentFacility as follows: 

![image](https://user-images.githubusercontent.com/13329248/121516429-7c50c680-c9ee-11eb-9897-dacdb599a4c1.png)

### Technical details
Related pull request: https://github.com/INSPIRE-MIF/application-schemas/pull/3

# Additional information

## Proposal reason
bugfix

## Addressed schema
https://inspire.ec.europa.eu/schemas/us-emf/4.0/EnvironmentalManagementFacilities.xsd

## Impact on INSPIRE TG / IR
No impact

### More detailed documentation

Relevant discussion in the INSPIRE Community Forum:
https://wayback.archive-it.org/12090/20210119192050/https://inspire.ec.europa.eu/forum/discussion/view/265816/error-in-the-environmental-management-facilities-application-schema

**Comment by sMorrone** [comment]
Subgroup meeting 01-07-2021: the sub-group approves the change proposal and invites the INSPIRE Coordination Team (CT) to endorse it.

**Comment by MarcoMinghini** [comment]
The INSPIRE MIG approved the change proposal, since no objections were raised during the two week scrutiny period from July 12 to July 26, 2021. The change can be now implemented.
