### ISSUE TITLE
US-net-tc_telecomunications xsd not on original URL

### ISSUE THREAD

**Issue by PalmJanssen** [INSPIRE-MIF/application-schemas#49]
The telecommunications.xsd has been removed from its original URL. We operate data services that reference this schema.
This action has an impact on our **legally mandated** cable and pipeline information services.

# Change proposal description
Quickly put the telcommunications.xsd back to its original URL to repair the unintended impact

## Issue faced
dead link since 16-11: http://inspire.ec.europa.eu/schemas/us-net-tc/4.0/TelecommunicationsNetwork.xsd

Validation and dataservices based on this schema fail to work.

### Current behaviour
dead link since 16-11: http://inspire.ec.europa.eu/schemas/us-net-tc/4.0/TelecommunicationsNetwork.xsd

## Proposed solution
move: https://inspire.ec.europa.eu/schemas/2021.1/us-net-tc/4.0/TelecommunicationsNetwork.xsd
back to: http://inspire.ec.europa.eu/schemas/us-net-tc/4.0/TelecommunicationsNetwork.xsd

### Technical details
 

# Additional information

## Proposal reason
Back ground:

In the Netherlands we run a cable and pipeline excavation damage data service based on INSPIRE data specs. The use of this service is legally mandated. The service uses the INSPIRE 4.0 xml schemas, for data specs and validation. It was noticed by operators that since nov 16 the telecom xsd was not available any more. This was communicated to Geonovum (the INSPIRE implementation coordinator and related cable and pipeline standard office).

What to do now? Our most optimal solution is that the XSD is placed back again to its original URL. This would evade a lot of communication and unforeseen complications.

By the way, we consider the use of these INSPIRE schema's a great example of an INSPIRE implementation success.

## Change proposer

Paul Janssen
Geonovum, Netherlands

### More detailed documentation
I noticed this event #37 related to this issue

**Comment by MarcoMinghini** [comment]
Dear @PalmJanssen,
in the [release 2021.2](https://github.com/INSPIRE-MIF/application-schemas/releases/tag/2021.2) of the INSPIRE schemas, we moved all the non-endorsed INSPIRE schemas that were still present in the directory https://inspire.ec.europa.eu/schemas. In particular, the schema us-net-tc/4.0/TelecommunicationsNetwork.xsd was moved in the draft-schemas folder (https://inspire.ec.europa.eu/draft-schemas/us-net-tc/4.0/TelecommunicationsNetwork.xsd), in addition to being included in the folder https://inspire.ec.europa.eu/schemas/2021.1/ which includes all the schemas as they were before the 2021.2 release.

To still preserve the rule of having only official INSPIRE schemas in the https://inspire.ec.europa.eu/schemas directory and to avoid breaking existing implementations, we implemented a redirection from http://inspire.ec.europa.eu/schemas/us-net-tc/4.0/TelecommunicationsNetwork.xsd (which does not exist anymore) to https://inspire.ec.europa.eu/draft-schemas/us-net-tc/4.0/TelecommunicationsNetwork.xsd. This should solve the issue with schema validation.

Best regards.

**Comment by PalmJanssen** [comment]
Dear @MarcoMinghini ,

Perfect. We have verified the solution and it is working fine.

Thank you for the quick action taken.

Paul
