### ISSUE TITLE
Add SLD capabilities schema to inspire_vs.xsd schema

### ISSUE THREAD

**Issue by petbod-lm** [INSPIRE-MIF/application-schemas#51]
# Change proposal description
Update inspire_vs.xsd schema to include the SLD capabilities schema to allow validation of WMS GetCapabilities documents

## Issue faced
Originaly report to INSPIRE-MIF : https://github.com/INSPIRE-MIF/helpdesk-validator/issues/616 
WMS GetCapabilites documents are not validated because the inspire_vs.xsd schema does not include the SLD schema

### Expected behaviour
WMS GetCapabilites documents should successfully validate in the ETF Validator

### Current behaviour
WMS GetCapabilites documents fail validation because the inspire_vs.xsd schema does not include the SLD schema

### Steps to reproduce
Validate the WMS service from Lantmäteriet (Sweden) in the ETF Validator with the service URL
https://maps.lantmateriet.se/capabilities/elf/basemap/wms/v1?request=GetCapabilities&service=WMS&version=1.3.0
Test that fails:
at04-getcapabilities-xml-schema-validation > check-xml-schema-valid

## Proposed solution
The inspire_vs.xsd schema should be modified to include the SLD capabilities schema (http://schemas.opengis.net/sld/1.1.0/sld_capabilities.xsd).

### Technical details
Pull request for inspire_vs.xsd to import SLD_Capabilities schema is here
https://github.com/INSPIRE-MIF/application-schemas/pull/50 

# Additional information

## Proposal reason
The current version of inspire_vs.xsd schema does not include the SLD Capabilities schema

## Addressed schema
https://inspire.ec.europa.eu/schemas/inspire_vs/1.0/inspire_vs.xsd

## Impact on INSPIRE TG / IR
No impact as far as I know

## Change proposer
Peter Bodley, Lantmäteriet, Sweden

### Available implementation
https://github.com/INSPIRE-MIF/application-schemas/pull/50

**Comment by sMorrone** [comment]
Subgroup Meeting 15-12-2021: Change proposal is approved

**Comment by MarcoMinghini** [comment]
The INSPIRE CT approved the change proposal during today's meeting. In the next step, the proposal will be moved to the MIG for the final endorsement.

**Comment by sMorrone** [comment]
During the joint MIG/MIG-T meeting held on 31/03-01/04/2022, the proposal was endorsed.
More details in the meeting minutes on the [69th MIG-T meeting page](https://wikis.ec.europa.eu/display/InspireMIG/69th+MIG-T+meeting+2022-04-01)
