### ISSUE TITLE
Add Norwegian and Icelandic languages to the common.xsd schema

### ISSUE THREAD

**Issue by sMorrone** [INSPIRE-MIF/application-schemas#59]
# Change proposal description
This issue is related to MD TG change proposal [#5](https://github.com/INSPIRE-MIF/technical-guidelines/issues/5), already endorsed by the MIG - see [comment](https://github.com/INSPIRE-MIF/technical-guidelines/issues/5#issuecomment-894272813).
Needed modifications to common.xsd have already been implemented in the [updated schema version](https://inspire-geoportal.ec.europa.eu/schemas/inspire/common/1.0/common.xsd) available in the geoportal repository, where also related [enum_nor.xsd](https://inspire-geoportal.ec.europa.eu/schemas/inspire/common/1.0/enums/enum_nor.xsd) and [enum_ice.xsd](https://inspire-geoportal.ec.europa.eu/schemas/inspire/common/1.0/enums/enum_ice.xsd) can be found.

## Proposed solution
The xsd files in the geoportal should be used to create a pull request to the schema repository.

# Additional information
The change proposal impacts on the Validator - see [issue #327](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/327#issue-636098786), [issue #706](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/706) and related [pull request #690](https://github.com/inspire-eu-validation/ets-repository/pull/690)

**Comment by sMorrone** [comment]
Dear @larsingea,
with reference to [validator issue 327](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/327#issue-636098786) could you please confirm that the [enum_nor.xsd](https://inspire-geoportal.ec.europa.eu/schemas/inspire/common/1.0/enums/enum_nor.xsd) in the geoportal is the correct / most updated version we can use to create the pull request? Thank you

**Comment by sMorrone** [comment]
Similar confirmation is needed for the [enum_ice.xsd](https://inspire-geoportal.ec.europa.eu/schemas/inspire/common/1.0/enums/enum_ice.xsd)

**Comment by sMorrone** [comment]
Subgroup meeting on 24.03.2022:
the Subgroup approved this change proposal.
However, confirmation is still needed that the enumeration files are correct ([enum_nor.xsd](https://inspire-geoportal.ec.europa.eu/schemas/inspire/common/1.0/enums/enum_nor.xsd) and [enum_ice. xsd](https://inspire-geoportal.ec.europa.eu/schemas/inspire/common/1.0/enums/enum_ice.xsd)).

**Comment by sMorrone** [comment]
During the joint MIG/MIG-T meeting held on 31/03-01/04/2022, the proposal was endorsed.
More details in the meeting minutes on the [69th MIG-T meeting page](https://wikis.ec.europa.eu/display/InspireMIG/69th+MIG-T+meeting+2022-04-01)

**Comment by sMorrone** [comment]
Since the correctness of the enumeration files ([enum_nor.xsd](https://inspire-geoportal.ec.europa.eu/schemas/inspire/common/1.0/enums/enum_nor.xsd) and [enum_ice. xsd](https://inspire-geoportal.ec.europa.eu/schemas/inspire/common/1.0/enums/enum_ice.xsd)) has not yet been confirmed, this change proposal won't be included in the 2022.2 release.  I am removing the 2022.2 milestone.

**Comment by larsingea** [comment]
> 

Dear @sMorrone 
I hereby confirm that the enum_nor.xsd is correct. I hope the file can be included in the next release. I have been in contact with Iceland, but they use English as metadata language, and are not very concerned about this issue.
