### ISSUE TITLE
US net thermal 4.0 xsd - thermalProductType is missing gml:ReferenceType type defintion

### ISSUE THREAD

**Issue by lucvanlinden** [INSPIRE-MIF/application-schemas#62]
HI

The GML application schema xsd, https://inspire.ec.europa.eu/schemas/us-net-th/4.0/ThermalNetwork.xsd
extends the us common pipe class with ThermalPipe.

The ThermalPipe gets a property thermalProductType, which is defined as a codelist according teh data specifications.

https://inspire.ec.europa.eu/codelist/ThermalProductTypeValue

However, the xsd GML application schema is missing its type defintion:

type="gml:ReferenceType" for this element thermalProductType.

<element name="thermalProductType" nillable="true">

which we believe should be

<element name="thermalProductType" type="gml:ReferenceType" nillable="true">

Can this be confirmed, if is confirmed, be corrected?

tx

Luc Van Linden

**Comment by sMorrone** [comment]
@lucvanlinden 
you are right. There is indeed a bug in the schema related to missing type definition for the element "thermalProductType" .

I am providing below few more details for the issue you identified : 

### Technical details
in the schema, the current 
element _name="thermalProductType" nillable="true"_
must be replaced by
_element name="thermalProductType"  **type="gml:ReferenceType"** nillable="true"_

## Addressed schema
https://inspire.ec.europa.eu/schemas/us-net-th/4.0/ThermalNetwork.xsd

## Impact on INSPIRE TG / IR
No impact

@lucvanlinden 
Can you please add details related to change proposer? i.e. Specify the submitting person, organisation or group of people/organisations?

Thank you

**Comment by lucvanlinden** [comment]
Luc Van Linden
HL Consulting - Belgium

**Comment by sMorrone** [comment]
Subgroup meeting on 24.03.2022:
the Subgroup approved this change proposal.
Exceptionally, given the proximity of the next MIG-T meeting, and in order to speed up the approval process, this change proposal that, following the governance process workflow, would have been responsibility of INSPIRE CT (whose meeting will be subsequent to that of the MIG-T) will be discussed in the MIG-T meeting.

**Comment by sMorrone** [comment]
During the joint MIG/MIG-T meeting held on 31/03-01/04/2022, the proposal was endorsed.
More details in the meeting minutes on the [69th MIG-T meeting page](https://wikis.ec.europa.eu/display/InspireMIG/69th+MIG-T+meeting+2022-04-01)
