### ISSUE TITLE
PF_type_missing xlink structure for codelist attribute

### ISSUE THREAD

**Issue by Dnoack49** [INSPIRE-MIF/application-schemas#64]
# Change proposal description
The attribute 'type'  is currently not modeled via xlink structure. 

## Issue faced
Commonly attributes with codelists should be modeled via xlink structure. However this is not the case for the two FeatureTypes _ProductionInstallation_ and _ProductionInstallationPart_.

## Proposed solution
A solution for the FeatureType _ProductionInstallation_ has already been proposed 2018 in the INSIPRE Thematic Cluster:
[Correction of the schema http://inspire.ec.europa.eu/schemas/pf/4.0/ProductionAndIndustrialFacilities.xsd](https://wayback.archive-it.org/12090/20210124022402/https://inspire.ec.europa.eu/forum/file/view/217764/correction-of-the-schema-httpinspireeceuropaeuschemaspf40productionandindustrialfacilitiesxsd)

It should be implemented for the FeatureType _ProductionInstallationPart_ respectively.

# Additional information

## Proposal reason
Bugfix

## Addressed schema
https://inspire.ec.europa.eu/schemas/pf/4.0/ProductionAndIndustrialFacilities.xsd

## Impact on INSPIRE TG / IR
No impact on TG/IR.

### Available implementation
Here a poposed fixed Schema for both FeatureTypes: [ProductionAndIndustrialFacilities_fixed.zip](https://github.com/INSPIRE-MIF/application-schemas/files/8246522/ProductionAndIndustrialFacilities_fixed.zip)

**Comment by Dnoack49** [comment]
PF_riverBasinDistrict_The attribute is wrong encoded #1

**Comment by sMorrone** [comment]
Dear @Dnoack49 , thank you for reporting this bug.
I am just adding below the technical details needed for the pull request:
### Technical details
in both feature types, the current definition
_element name="type" nillable="true"_
shall be replaced by
_element name="type" nillable="true" type="gml:ReferenceType"_

**Comment by sMorrone** [comment]
Subgroup meeting on 24.03.2022:
the Subgroup approved this change proposal.
Exceptionally, given the proximity of the next MIG-T meeting, and in order to speed up the approval process, this change proposal that, following the governance process workflow, would have been responsibility of INSPIRE CT (whose meeting will be subsequent to that of the MIG-T) will be discussed in the MIG-T meeting.

**Comment by sMorrone** [comment]
During the joint MIG/MIG-T meeting held on 31/03-01/04/2022, the proposal was endorsed.
More details in the meeting minutes on the [69th MIG-T meeting page](https://wikis.ec.europa.eu/display/InspireMIG/69th+MIG-T+meeting+2022-04-01)
