### ISSUE TITLE
ER_dateOfDetermination&dateOfDiscovery_missing nilreason

### ISSUE THREAD

**Issue by Dnoack49** [INSPIRE-MIF/application-schemas#65]
# Change proposal description
In May 2020 the issue [Energy Resources: Missing nilReason for dateOfDetermination and dateOfDiscovery](https://wayback.archive-it.org/12090/20210124005818/https://inspire.ec.europa.eu/forum/discussion/view/266025/energy-resources-missing-nilreason-for-dateofdetermination-and-dateofdiscovery) was opened in the INSPIRE Thematic Cluster. As it has not been solved this git issue was created.

## Issue faced
The Energy Resources vector schema has issues concerning two properties that are defined differently in the according [UML model ](https://inspire.ec.europa.eu/data-model/approved/r4618-ir/html/EARoot/EA2/EA3/EA7/EA2/EA8296.htm):
1. RenewableAndWasteResource.dateOfDetermination: is missing nilReason definition (attribute nillable is set to 'true' for it though)
2. FossilFuelResource.dateOfDiscovery: is missing nilReason definition (attribute nillable is set to 'true' for it though)

# Additional information

## Proposal reason
Bugfix

## Addressed schema
https://inspire.ec.europa.eu/schemas/er-v/4.0/EnergyResourcesVector.xsd

## Impact on INSPIRE TG / IR
No impact on TG/IR.

**Comment by fabiovinci** [comment]
Dear @Dnoack49,

thank you for opening the issue.

Looking at your proposal it seems the errors are the followings:

- RenewableAndWasteResource.dateOfDetermination: is missing nilReason definition (attribute nillable is set to 'true' for it though)
- FossilFuelResource.dateOfDiscovery: is missing nilReason definition (attribute nillable is set to 'true' for it though)

Moreover, the addressed schema should be: https://inspire.ec.europa.eu/schemas/er-v/4.0/EnergyResourcesVector.xsd

Could you please check and edit your comment?
Thanks

**Comment by Dnoack49** [comment]
Dear @fabiovinci ,
ok, I have edited my comment.

**Comment by sMorrone** [comment]
Subgroup meeting on 24.03.2022:
the Subgroup approves this change proposal. 
Exceptionally, given the proximity of the next MIG-T meeting, and in order to speed up the approval process, this change proposal that, following the governance process workflow, would have been responsibility of INSPIRE CT (whose meeting will be subsequent to that of the MIG-T) will be discussed in the MIG-T meeting.

**Comment by heidivanparys** [comment]
> In particular, since the nilReason attribute should be added by extension of the type 'TimePositionType', this is not possible because the 'TimePositionType' forbids derivation by extension.

I did some research and noted that this issue was observed as well during the work done in the OGC OWS-6 Interoperability Testbed. One of the engineering reports, [OGC OWS-6-AIM Engineering Report](https://portal.ogc.org/files/34032), links to a change request, [OGC 09-023r1](http://portal.opengeospatial.org/files/?artifact_id=32663), that contains the following comment:

> It was also noted that the “unknown” enumeration value provides a reason for a nil element value, hence attention is drawn to the possibility of adding the `nilReason` attribute with `type='gml:NilReasonEnumeration'` to `gml:TimePositionType` in lieu of the   `unknown` enumeration value in `TimeIndeterminateValueType` and for consistency with other GML property types.

However, this, and the actual change proposal in that document, does not seem to have been addressed by OGC. If the INSPIRE thinks this change is needed, I guess the correct way would be to create a new change proposal in the [OGC Standards Tracker](http://ogc.standardstracker.org/requestlist.cgi?quicksearch=07-036).

> However using the dataType "TM_Position" inexact temporal positions may be expressed using the optional indeterminatePosition attribute

If the attribute is nillable, `xsi:nil` can be used as usual:

```xml
<er-v:dateOfDetermination xsi:nil="true" />
```
which has the same meaning as

```xml
<er-v:dateOfDetermination indeterminatePosition="unknown" />
```

> An alternative solution could be (but we would not reconmend this) to propose a change in the data type of the two attributes using, for example, the "dateTime" or "date" dataTypes.

I assume that the reason certain data specification use `TM_Position` is that it allows choosing between providing a date or a datetime, and not so much the capability of being able to provide an “indeterminate position”. E.g. from the [TG AM](https://inspire.ec.europa.eu/id/document/tg/am):

> The values that can be defined are flexible. The beginPosition and endPosition use the TM_Position
> type which is a union of ISO 8601 Date, Time or DateTime.

**Comment by doemming** [comment]
this looks good to me.

Just a minor edit: I think the empty element using `indeterminatePosition="unknown"` would require also to set `xsi:nil="true"` like this:

`<er-v:dateOfDetermination indeterminatePosition="unknown" xsi:nil="true" />`

**Comment by sMorrone** [comment]
`<er-v:dateOfDetermination indeterminatePosition="unknown" xsi:nil="true" /> is a third option indeed.

**Summing up:**

- _**<er-v:dateOfDetermination indeterminatePosition="unknown"/>**_ indicates that no specific value for temporal position is provided (as per description of "unknown" value in the gml:TimeIndeterminateValueType enum)

- _**<er-v:dateOfDetermination xsi:nil="true" />**_ indicates that the element does not have a value 

- _**<er-v:dateOfDetermination indeterminatePosition="unknown" xsi:nil="true" />**_ indicates that no specific value for temporal position is provided and that the element does not have a value

**Comment by pawelsoczewski** [comment]
> <er-v:dateOfDetermination indeterminatePosition="unknown" xsi:nil="true" /> is a third option indeed.
> 
> **Summing up** there are three valid options:
> 
> * _**<er-v:dateOfDetermination indeterminatePosition="unknown"/>**_ indicates that no specific value for temporal position is provided (as per description of "unknown" value in the gml:TimeIndeterminateValueType enum)
> * _**<er-v:dateOfDetermination xsi:nil="true" />**_ indicates that the schema element does not have a value
> * _**<er-v:dateOfDetermination indeterminatePosition="unknown" xsi:nil="true" />**_ indicates that no specific value for temporal position is provided and that the schema element does not have a value

Technically, all of the above options are valid, but according to _Voidable characteristics_ only three option are possible:

![Zrzut ekranu 2022-04-1 o 08 04 07](https://user-images.githubusercontent.com/44895671/161204549-64d45abd-2068-4908-8a60-7049ad086ed3.png)

Therefore options 1 and 3 - using only indeterminatePosition = "unknown" can be slightly confusing and will not always match the definitions above. The void value "unknown" can only be used in a specific case.

In my opinion recommendation of sub-group should be option 2th: "With current schema version, recommendation is either to set the xsi:nil="true" to indicate that the value for the dateOfDetermination /dateOfDiscovery element is not provided /is unknown".

**Comment by sMorrone** [comment]
Subgroup meeting on 13.09.2022:
This issue can be closed as soon as the related content will be summarised and made available as implementation example in the Discussions tab of the generic helpdesk.

**Comment by sMorrone** [comment]
Related "Implementation examples" category discussion: https://github.com/INSPIRE-MIF/helpdesk/discussions/134
