### ISSUE TITLE
GE_HydrogeologicalObject_HydrogeologicalObjectManMade_missing nillable attribute

### ISSUE THREAD

**Issue by JohannaOtt** [INSPIRE-MIF/application-schemas#73]
# Change proposal description
Add nillable attribute to HydrogeologicalObject.beginLifespanVersion and HydrogeologicalObjectManMade.validFrom in [hydrogeology schema](https://inspire.ec.europa.eu/schemas/ge_hg/4.0/HydrogeologyCore.xsd). Not sure if more actions are required to correctly implement the model from the  [UML diagram](https://inspire.ec.europa.eu/data-model/approved/r4618-ir/html/EARoot/EA2/EA2/EA2/EA2/EA7766.htm).

## Issue faced
According to the UML diagram, both elements mentioned are voidable. That is not respected in the xsd and therefore, no nilReason can be provided.

### Expected behaviour
It is possible to provide nilReason values for both voidable elements.

### Current behaviour
It is not possible to provide nilReason values.

## Proposal reason
Requirements cannot be fulfilled.

## Addressed schema
https://inspire.ec.europa.eu/schemas/ge_hg/4.0/HydrogeologyCore.xsd

## Change proposer
Johanna Ott (wetransform GmbH) for WIZIPISI (The Wroclaw Institute of Spatial Information and Artificial Intelligence)

**Comment by fabiovinci** [comment]
Dear @JohannaOtt,

thank you for opening the issue.

It seems that the nillable attribute is also missing for the HydrogeologicalObject.endLifespanVersion and HydrogeologicalObjectManMade.validTo attributes.

**Comment by heidivanparys** [comment]
This should also be fixed in the UML model. Those properties have the wrong stereotype:

![image](https://user-images.githubusercontent.com/11427611/198342789-6123b403-8674-40ca-a1ef-3bf529b67051.png)

![image](https://user-images.githubusercontent.com/11427611/198342901-fb46a488-c91c-47d6-ba5d-f23faf8da165.png)

![image](https://user-images.githubusercontent.com/11427611/198342653-bb17aa8f-3699-4fdc-b39b-afdca4b379b9.png)

![image](https://user-images.githubusercontent.com/11427611/198343111-88502151-ab48-4174-857c-7d71c778743c.png)

**Comment by sMorrone** [comment]
On Nov 4th, 2022, the sub-group approved, after a consultation via mail.

**Comment by JohannaOtt** [comment]
@sMorrone Does that mean that the [PR addressing the issue](https://github.com/INSPIRE-MIF/application-schemas/pull/74) could/should be merged in order to update the xsd provided in the repository?

**Comment by sMorrone** [comment]
Dear @JohannaOtt
according to the [governance and release process for changes to the INSPIRE schemas](https://github.com/INSPIRE-MIF/application-schemas/blob/main/governance-release-process/process.md), once approved by the sub-group a change proposal needs approval by the INSPIRE CT /MIG-T and then final endorsement by the MIG. Should this be the case for this change proposal, it will be implemented (i.e. the PR will be merged and the xsd updated) in the next release of schemas foreseen by Jan 31st.

**Comment by fabiovinci** [comment]
During the joint MIG/MIG-T meeting held on 24-25/11/2022, the proposal was endorsed.
More details in the meeting minutes on the [72nd MIG-T meeting page](https://wikis.ec.europa.eu/display/InspireMIG/72nd+MIG-T+meeting+2022-11-25).
