### ISSUE TITLE
SO_missing associations to OM_Observation

### ISSUE THREAD

**Issue by sMorrone** [INSPIRE-MIF/application-schemas#8]
# Change proposal description
Proposal is twofold: 

1. modify the schema in the official repository adding the associations to OM_Observation objects foreseen in the IR (associations are present in the draft repository schema version);
2. modify the soilDerivedObjectObservation multiplicity from 1 to [1..*].  

## Issue faced
In the official schema,
- SoilSite is missing association soilSiteObservation with target OM_Observation
- SoilProfile is missing association soilProfileObservation with target OM_Observation
- ProfileElement is missing association profileElementObservation with target OM_Observation
- SoilDerivedObject is missing association soilDerivedObjectObservation with target OM_Observation

The soilDerivedObjectObservation multiplicity is 1. This means that if a SoilDerivedObject has **n** observations linked to it, one is forced to provide this same object **n** times.

As a side note, all the other abovementioned associations allow provision of multiple observations (multiplicity 0..*)

### Expected behaviour

1. It is possible to provide the associations to OM_Observation objects using the official schema; 
2. Same _SoilDerivedObject_ can be linked to more observations.

### Current behaviour

1. The associations to OM_Observation are included only in the schema in the draft repository, so it is not possible to provide them using the official schema;
2. The multiplicity of the soilDerivedObjectObservation  is set to 1, so one is forced to create a soilDerivedObject for every observation related to it.

## Proposed solution
Modify the schema in the draft repository regarding the multiplicity of the soilDerivedObjectObservation and endorse this as official schema.

### Technical details
the soilDerivedObjectObservation in the draft schema should be modified adding **_maxOccurs="unbounded" minOccurs="1"_** to current definition.

related Pull Request #18
# Additional information

## Proposal reason
The first point of this change proposal is needed because of a bug in the official schema
The second point is an enhancement to current model

## Addressed schema
https://inspire.ec.europa.eu/schemas/so/4.0/Soil.xsd

## Impact on INSPIRE TG / IR
TG should be updated so that multiplicity for the "soilDerivedObjectObservation" is set to [1..*]

## Change proposer

- Inspire Community Forum request for the bug fixing of the schema related to missing associations to OM_Observation (i.e. alignment of schema to IR and TG)
- Geological Survey of Sweden regarding the change to the multiplicity for the "soilDerivedObjectObservation" association. Original proposal was to change multiplicity to 0..* but, after community discussions in the Thematic Clusters, agreement was on 1..*.

### More detailed documentation
https://wayback.archive-it.org/12090/20161216062201/https://themes.jrc.ec.europa.eu/discussion/view/3421/inspire-soil-theme-change-of-the-multiplicity-of-the-soilderivedobjectobservation

https://wayback.archive-it.org/12090/20210119211852/https://inspire.ec.europa.eu/forum/discussion/view/186450/missing-associations-to-om-observation-in-xsd

**Comment by sMorrone** [comment]
Subgroup meeting 01-07-2021: the sub-group approves the change proposal and invites the INSPIRE MIG-T to endorse it.

**Comment by MarcoMinghini** [comment]
The INSPIRE MIG-T approved the change proposal during the [66th MIG-T meeting](https://webgate.ec.europa.eu/fpfis/wikis/pages/viewpage.action?pageId=803309194). In the next step, the proposal will be moved to the MIG for the final endorsement.
