### ISSUE TITLE
US_UtilityNetwork_authorityRole RelatedParty type to reference inline

### ISSUE THREAD

**Issue by mquanz** [INSPIRE-MIF/application-schemas#83]
# Change proposal description
In the "UtilityNetwork" FeatureType (application scheme "Common Utility Network Elements") the data type of "authorityRole" is defined by the implementation rules and INSPIRE model as "RelatedParty". This is implemented in the INSPIRE schema XSD in form of a gml:ReferenceType. 

Extract from the XSD:
`<element maxOccurs="unbounded" name="authorityRole" type="gml:ReferenceType">`

However a reference can only be set to a feature type, not to a data type. As it is not possible to create a RelatedParty object on top level in a gml:FeatureCollection, this is indeed a problem.

I suggest to change the schema that RelatedParty objects can be created inline.

## Issue faced
RelatedParty objects cannot be referenced.

### Expected behaviour
RelatedParty objects can be created inline.

### Current behaviour
RelatedParty objects cannot be referenced.

## Proposed solution
I suggest to change the schema that RelatedParty objects can be created inline.

# Additional information

## Proposal reason
This change proposal is needed because the schema model does not fit the purpose.

## Addressed schema
[us-net-common](https://github.com/INSPIRE-MIF/application-schemas/blob/main/schemas/us-net-common/4.0/UtilityNetworksCommon.xsd)

## Change proposer
Martin Quanz

### More detailed documentation

**Comment by fabiovinci** [comment]
Dear @mquanz,

thank you for opening the issue.
It seems that the datatype of the "authorityRole" attribute is not correct.
We will have a look asap.

**Comment by sMorrone** [comment]
Just adding details of required schema change:
current definition
`<element maxOccurs="unbounded" name="authorityRole" type="gml:ReferenceType">`
should be replaced by
  ```
<element maxOccurs="unbounded" name="authorityRole">
           <complexType>
              <sequence>
                <element ref="base2:RelatedParty"/>
              </sequence>
           </complexType>
    </element>
```

**Comment by fabiovinci** [comment]
The sub-group approved this change proposal after consultation by email.
Since it was classified as a "trivial change", it can be directly implemented by JRC.
